services:
  emerald-plant-tracker:
    image: dmans218/emerald-plant-tracker:latest
    container_name: emerald-plant-tracker
    ports:
      - 420:420
    volumes:
      - emerald_data:/app/backend/data
      - emerald_uploads:/app/backend/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/app/backend/data/emerald-plant-tracker.db
    restart: unless-stopped
    user: "1000:1000"  # Run as user with proper permissions
volumes:
  emerald_data:
  emerald_uploads:
networks: {} 