// Official nutrient data based on manufacturer feeding charts
// Sources: General Hydroponics, Advanced Nutrients, CANNA official documentation

const nutrientBrands = {
  'general-hydroponics': {
    name: 'General Hydroponics FloraSeries',
    description: 'The O.G. 3-Part Hydroponic-Based Nutrient System',
    products: {
      seedling: [
        { name: 'FloraMicro', ratio: 2.0, unit: 'ml/gal' },
        { name: 'FloraGro', ratio: 2.0, unit: 'ml/gal' },
        { name: 'FloraBloom', ratio: 2.0, unit: 'ml/gal' },
      ],
      vegetative: [
        { name: 'FloraMicro', ratio: 6.8, unit: 'ml/gal' },
        { name: 'FloraGro', ratio: 6.4, unit: 'ml/gal' },
        { name: 'FloraBloom', ratio: 4.8, unit: 'ml/gal' },
      ],
      flowering: [
        { name: 'FloraMicro', ratio: 5.3, unit: 'ml/gal' },
        { name: 'FloraGro', ratio: 5.3, unit: 'ml/gal' },
        { name: 'FloraBloom', ratio: 7.6, unit: 'ml/gal' },
      ],
      supplements: [
        { name: 'CaliMagic', ratio: 5.0, unit: 'ml/gal', optional: true },
        { name: 'Armor Si', ratio: 2.5, unit: 'ml/gal', optional: true },
        { name: 'Hydroguard', ratio: 2.0, unit: 'ml/gal', hydroOnly: true },
        {
          name: 'RapidStart',
          ratio: 2.5,
          unit: 'ml/gal',
          optional: true,
          earlyGrowth: true,
        },
        {
          name: 'Liquid KoolBloom',
          ratio: 2.5,
          unit: 'ml/gal',
          optional: true,
          floweringOnly: true,
        },
        {
          name: 'Floralicious Plus',
          ratio: 1.0,
          unit: 'ml/gal',
          optional: true,
        },
        {
          name: 'FloraKleen',
          ratio: 10.0,
          unit: 'ml/gal',
          optional: true,
          flushOnly: true,
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.5, medium: 0.7, aggressive: 0.9 },
      vegetative: { light: 1.0, medium: 1.4, aggressive: 1.8 },
      flowering: { light: 1.2, medium: 1.6, aggressive: 2.0 },
    },
    targetTDS: {
      seedling: { light: 250, medium: 350, aggressive: 450 },
      vegetative: { light: 500, medium: 700, aggressive: 900 },
      flowering: { light: 600, medium: 800, aggressive: 1000 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
    weeklySchedule: {
      vegetative: {
        week1: { micro: 2.0, gro: 2.0, bloom: 2.0 },
        week2: { micro: 4.2, gro: 3.8, bloom: 3.0 },
        week3: { micro: 5.6, gro: 5.2, bloom: 3.8 },
        week4: { micro: 6.8, gro: 6.4, bloom: 4.8 },
      },
      flowering: {
        week1: { micro: 6.1, gro: 5.3, bloom: 4.8 },
        week2: { micro: 6.1, gro: 5.3, bloom: 4.8 },
        week3: { micro: 5.3, gro: 5.3, bloom: 7.6 },
        week4: { micro: 5.3, gro: 5.3, bloom: 7.6 },
        week5: { micro: 5.3, gro: 4.6, bloom: 7.6 },
        week6: { micro: 5.3, gro: 4.6, bloom: 7.6 },
        week7: { micro: 3.8, gro: 3.8, bloom: 4.6 },
        flush: { micro: 0, gro: 0, bloom: 0 },
      },
    },
  },
  'advanced-nutrients': {
    name: 'Advanced Nutrients pH Perfect GMB',
    description: 'pH Perfect Technology for Cannabis - Micro/Grow/Bloom',
    products: {
      seedling: [
        { name: 'pH Perfect Micro', ratio: 1.0, unit: 'ml/L' },
        { name: 'pH Perfect Grow', ratio: 1.0, unit: 'ml/L' },
        { name: 'pH Perfect Bloom', ratio: 1.0, unit: 'ml/L' },
      ],
      vegetative: [
        { name: 'pH Perfect Micro', ratio: 4.0, unit: 'ml/L' },
        { name: 'pH Perfect Grow', ratio: 4.0, unit: 'ml/L' },
        { name: 'pH Perfect Bloom', ratio: 4.0, unit: 'ml/L' },
      ],
      flowering: [
        { name: 'pH Perfect Micro', ratio: 4.0, unit: 'ml/L' },
        { name: 'pH Perfect Grow', ratio: 4.0, unit: 'ml/L' },
        { name: 'pH Perfect Bloom', ratio: 4.0, unit: 'ml/L' },
      ],
      supplements: [
        {
          name: 'Voodoo Juice',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          week: [1, 2, 3, 4],
        },
        { name: 'B-52', ratio: 2.0, unit: 'ml/L', optional: true },
        {
          name: 'Big Bud',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
          week: [2, 3, 4],
        },
        {
          name: 'Overdrive',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
          week: [5, 6],
        },
        {
          name: 'Bud Candy',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
        },
        { name: 'Rhino Skin', ratio: 2.0, unit: 'ml/L', optional: true },
        { name: 'Sensizym', ratio: 2.0, unit: 'ml/L', optional: true },
        {
          name: 'Bud Ignitor',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
          week: [1, 2],
        },
        {
          name: 'Flawless Finish',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          flushOnly: true,
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.4, medium: 0.6, aggressive: 0.8 },
      vegetative: { light: 1.0, medium: 1.4, aggressive: 1.8 },
      flowering: { light: 1.2, medium: 1.6, aggressive: 2.0 },
    },
    targetTDS: {
      seedling: { light: 200, medium: 300, aggressive: 400 },
      vegetative: { light: 500, medium: 700, aggressive: 900 },
      flowering: { light: 600, medium: 800, aggressive: 1000 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
    weeklySchedule: {
      vegetative: {
        week1: { micro: 1.0, grow: 1.0, bloom: 1.0 },
        week2: { micro: 2.0, grow: 2.0, bloom: 2.0 },
        week3: { micro: 3.0, grow: 3.0, bloom: 3.0 },
        week4: { micro: 4.0, grow: 4.0, bloom: 4.0 },
      },
      flowering: {
        week1: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week2: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week3: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week4: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week5: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week6: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        week7: { micro: 4.0, grow: 4.0, bloom: 4.0 },
        flush: { micro: 0, grow: 0, bloom: 0 },
      },
    },
  },
  'fox-farm': {
    name: 'Fox Farm Trio',
    description: 'Natural & Organic Based Plant Food',
    products: {
      seedling: [{ name: 'Big Bloom', ratio: 6.0, unit: 'ml/gal' }],
      vegetative: [
        { name: 'Grow Big', ratio: 10.0, unit: 'ml/gal' },
        { name: 'Big Bloom', ratio: 15.0, unit: 'ml/gal' },
      ],
      flowering: [
        { name: 'Tiger Bloom', ratio: 10.0, unit: 'ml/gal' },
        { name: 'Big Bloom', ratio: 15.0, unit: 'ml/gal' },
        { name: 'Grow Big', ratio: 5.0, unit: 'ml/gal', earlyFlower: true },
      ],
      supplements: [
        { name: 'Cal-Mag', ratio: 5.0, unit: 'ml/gal', optional: true },
        {
          name: 'Open Sesame',
          ratio: 0.25,
          unit: 'tsp/gal',
          optional: true,
          floweringOnly: true,
          week: [1, 2],
        },
        {
          name: 'Beastie Bloomz',
          ratio: 0.25,
          unit: 'tsp/gal',
          optional: true,
          floweringOnly: true,
          week: [3, 4, 5],
        },
        {
          name: 'Cha Ching',
          ratio: 0.25,
          unit: 'tsp/gal',
          optional: true,
          floweringOnly: true,
          week: [6, 7],
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.5, medium: 0.7, aggressive: 0.9 },
      vegetative: { light: 0.9, medium: 1.4, aggressive: 1.8 },
      flowering: { light: 1.2, medium: 1.7, aggressive: 2.2 },
    },
    targetTDS: {
      seedling: { light: 250, medium: 350, aggressive: 450 },
      vegetative: { light: 450, medium: 700, aggressive: 900 },
      flowering: { light: 600, medium: 850, aggressive: 1100 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
  canna: {
    name: 'CANNA Coco',
    description: 'Specifically designed for Coco Coir',
    products: {
      seedling: [
        { name: 'Canna Coco A', ratio: 2.0, unit: 'ml/L' },
        { name: 'Canna Coco B', ratio: 2.0, unit: 'ml/L' },
      ],
      vegetative: [
        { name: 'Canna Coco A', ratio: 3.0, unit: 'ml/L' },
        { name: 'Canna Coco B', ratio: 3.0, unit: 'ml/L' },
      ],
      flowering: [
        { name: 'Canna Coco A', ratio: 3.5, unit: 'ml/L' },
        { name: 'Canna Coco B', ratio: 3.5, unit: 'ml/L' },
      ],
      supplements: [
        {
          name: 'Rhizotonic',
          ratio: 4.0,
          unit: 'ml/L',
          optional: true,
          earlyGrowth: true,
        },
        { name: 'Cannazym', ratio: 2.5, unit: 'ml/L', optional: true },
        {
          name: 'Cannaboost',
          ratio: 2.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
        },
        {
          name: 'PK 13/14',
          ratio: 1.5,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
          week: [4],
        },
      ],
    },
    strengthMultipliers: {
      light: 0.6,
      medium: 0.8,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.7, medium: 0.9, aggressive: 1.1 },
      vegetative: { light: 1.1, medium: 1.3, aggressive: 1.5 },
      flowering: { light: 1.4, medium: 1.7, aggressive: 2.0 },
    },
    targetTDS: {
      seedling: { light: 350, medium: 450, aggressive: 550 },
      vegetative: { light: 550, medium: 650, aggressive: 750 },
      flowering: { light: 700, medium: 850, aggressive: 1000 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
    weeklySchedule: {
      vegetative: {
        week1: { a: 2.0, b: 2.0 },
        week2: { a: 2.5, b: 2.5 },
        week3: { a: 3.0, b: 3.0 },
        week4: { a: 3.5, b: 3.5 },
      },
      flowering: {
        week1: { a: 3.5, b: 3.5 },
        week2: { a: 4.0, b: 4.0 },
        week3: { a: 4.0, b: 4.0 },
        week4: { a: 4.0, b: 4.0 },
        week5: { a: 3.0, b: 3.0 },
        week6: { a: 3.0, b: 3.0 },
        week7: { a: 2.5, b: 2.5 },
        flush: { a: 0, b: 0 },
      },
    },
  },
  'jack-nutrients': {
    name: "Jack's Nutrients 321",
    description: 'Professional Dry Nutrients - Ultra Concentrated',
    products: {
      seedling: [
        { name: "Jack's 5-12-26", ratio: 1.8, unit: 'g/gal' },
        { name: 'Epsom Salt', ratio: 0.6, unit: 'g/gal' },
        { name: 'Calcium Nitrate', ratio: 1.2, unit: 'g/gal' },
      ],
      vegetative: [
        { name: "Jack's 5-12-26", ratio: 3.6, unit: 'g/gal' },
        { name: 'Epsom Salt', ratio: 1.2, unit: 'g/gal' },
        { name: 'Calcium Nitrate', ratio: 2.4, unit: 'g/gal' },
      ],
      flowering: [
        { name: "Jack's 5-12-26", ratio: 3.6, unit: 'g/gal' },
        { name: 'Epsom Salt', ratio: 1.2, unit: 'g/gal' },
        { name: 'Calcium Nitrate', ratio: 2.4, unit: 'g/gal' },
      ],
      supplements: [
        {
          name: "Jack's Bloom 10-30-20",
          ratio: 3.5,
          unit: 'g/gal',
          optional: true,
          floweringOnly: true,
        },
        {
          name: 'MKP (0-52-34)',
          ratio: 0.5,
          unit: 'g/gal',
          optional: true,
          floweringOnly: true,
          week: [4, 5],
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.8,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.4, medium: 0.6, aggressive: 0.8 },
      vegetative: { light: 1.0, medium: 1.5, aggressive: 2.0 },
      flowering: { light: 1.2, medium: 1.7, aggressive: 2.2 },
    },
    targetTDS: {
      seedling: { light: 200, medium: 300, aggressive: 400 },
      vegetative: { light: 500, medium: 750, aggressive: 1000 },
      flowering: { light: 600, medium: 850, aggressive: 1100 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
  megacrop: {
    name: 'MegaCrop by Greenleaf',
    description: 'All-in-One Complete Nutrient - Seed to Harvest',
    products: {
      seedling: [{ name: 'MegaCrop', ratio: 2.5, unit: 'g/gal' }],
      vegetative: [{ name: 'MegaCrop', ratio: 5.0, unit: 'g/gal' }],
      flowering: [{ name: 'MegaCrop', ratio: 6.0, unit: 'g/gal' }],
      supplements: [
        {
          name: 'Bud Explosion PK',
          ratio: 1.0,
          unit: 'g/gal',
          optional: true,
          floweringOnly: true,
        },
        { name: 'Sweet Candy', ratio: 0.5, unit: 'g/gal', optional: true },
        { name: 'CalMag Pro', ratio: 1.0, unit: 'g/gal', optional: true },
        {
          name: 'Sea-K',
          ratio: 0.5,
          unit: 'g/gal',
          optional: true,
          floweringOnly: true,
        },
      ],
    },
    strengthMultipliers: {
      light: 0.7,
      medium: 0.85,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.5, medium: 0.7, aggressive: 0.9 },
      vegetative: { light: 1.0, medium: 1.4, aggressive: 1.8 },
      flowering: { light: 1.2, medium: 1.6, aggressive: 2.0 },
    },
    targetTDS: {
      seedling: { light: 250, medium: 350, aggressive: 450 },
      vegetative: { light: 500, medium: 700, aggressive: 900 },
      flowering: { light: 600, medium: 800, aggressive: 1000 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
    weeklySchedule: {
      vegetative: {
        week1: { megacrop: 2.0 },
        week2: { megacrop: 3.0 },
        week3: { megacrop: 4.0 },
        week4: { megacrop: 5.0 },
      },
      flowering: {
        week1: { megacrop: 5.5 },
        week2: { megacrop: 6.0 },
        week3: { megacrop: 6.0 },
        week4: { megacrop: 6.0 },
        week5: { megacrop: 6.0 },
        week6: { megacrop: 5.5 },
        week7: { megacrop: 5.0 },
        flush: { megacrop: 0 },
      },
    },
  },
  botanicare: {
    name: 'Botanicare Pure Blend Pro',
    description: 'Premium Natural & Organic Based Nutrients',
    products: {
      seedling: [{ name: 'Pure Blend Pro Grow', ratio: 5.0, unit: 'ml/gal' }],
      vegetative: [
        { name: 'Pure Blend Pro Grow', ratio: 15.0, unit: 'ml/gal' },
      ],
      flowering: [
        { name: 'Pure Blend Pro Bloom', ratio: 15.0, unit: 'ml/gal' },
      ],
      supplements: [
        { name: 'Cal-Mag Plus', ratio: 5.0, unit: 'ml/gal', optional: true },
        { name: 'Hydroguard', ratio: 2.0, unit: 'ml/gal', hydroOnly: true },
        { name: 'Liquid Karma', ratio: 10.0, unit: 'ml/gal', optional: true },
        {
          name: 'Sweet Raw',
          ratio: 5.0,
          unit: 'ml/gal',
          optional: true,
          floweringOnly: true,
        },
        {
          name: 'Hydroplex',
          ratio: 5.0,
          unit: 'ml/gal',
          optional: true,
          floweringOnly: true,
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.4, medium: 0.6, aggressive: 0.8 },
      vegetative: { light: 0.8, medium: 1.2, aggressive: 1.6 },
      flowering: { light: 1.0, medium: 1.4, aggressive: 1.8 },
    },
    targetTDS: {
      seedling: { light: 200, medium: 300, aggressive: 400 },
      vegetative: { light: 400, medium: 600, aggressive: 800 },
      flowering: { light: 500, medium: 700, aggressive: 900 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
  'dyna-gro': {
    name: 'Dyna-Gro Foliage Pro + Bloom',
    description: 'Simple 2-Part System - Complete Nutrition',
    products: {
      seedling: [{ name: 'Foliage Pro 9-3-6', ratio: 2.5, unit: 'ml/gal' }],
      vegetative: [{ name: 'Foliage Pro 9-3-6', ratio: 5.0, unit: 'ml/gal' }],
      flowering: [{ name: 'Bloom 3-12-6', ratio: 5.0, unit: 'ml/gal' }],
      supplements: [
        {
          name: 'Pro-TeKt (Silica)',
          ratio: 2.5,
          unit: 'ml/gal',
          optional: true,
        },
        { name: 'Mag-Pro', ratio: 2.5, unit: 'ml/gal', optional: true },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.3, medium: 0.5, aggressive: 0.7 },
      vegetative: { light: 0.8, medium: 1.2, aggressive: 1.6 },
      flowering: { light: 1.0, medium: 1.4, aggressive: 1.8 },
    },
    targetTDS: {
      seedling: { light: 150, medium: 250, aggressive: 350 },
      vegetative: { light: 400, medium: 600, aggressive: 800 },
      flowering: { light: 500, medium: 700, aggressive: 900 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
  'house-garden': {
    name: 'House & Garden Aqua Flakes',
    description: 'Premium Dutch Nutrients - Tested on Cannabis',
    products: {
      seedling: [
        { name: 'Aqua Flakes A', ratio: 1.5, unit: 'ml/L' },
        { name: 'Aqua Flakes B', ratio: 1.5, unit: 'ml/L' },
      ],
      vegetative: [
        { name: 'Aqua Flakes A', ratio: 2.7, unit: 'ml/L' },
        { name: 'Aqua Flakes B', ratio: 2.7, unit: 'ml/L' },
      ],
      flowering: [
        { name: 'Aqua Flakes A', ratio: 2.7, unit: 'ml/L' },
        { name: 'Aqua Flakes B', ratio: 2.7, unit: 'ml/L' },
      ],
      supplements: [
        {
          name: 'Roots Excelurator',
          ratio: 1.1,
          unit: 'ml/L',
          optional: true,
          earlyGrowth: true,
        },
        { name: 'Algen Extract', ratio: 1.0, unit: 'ml/L', optional: true },
        {
          name: 'Bud XL',
          ratio: 1.0,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
        },
        {
          name: 'Top Booster',
          ratio: 0.5,
          unit: 'ml/L',
          optional: true,
          floweringOnly: true,
          week: [5, 6, 7],
        },
        {
          name: 'Shooting Powder',
          ratio: 0.065,
          unit: 'g/L',
          optional: true,
          floweringOnly: true,
          week: [6, 7],
        },
      ],
    },
    strengthMultipliers: {
      light: 0.6,
      medium: 0.8,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.4, medium: 0.6, aggressive: 0.8 },
      vegetative: { light: 1.0, medium: 1.4, aggressive: 1.8 },
      flowering: { light: 1.2, medium: 1.6, aggressive: 2.0 },
    },
    targetTDS: {
      seedling: { light: 200, medium: 300, aggressive: 400 },
      vegetative: { light: 500, medium: 700, aggressive: 900 },
      flowering: { light: 600, medium: 800, aggressive: 1000 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
  'nectar-gods': {
    name: 'Nectar for the Gods',
    description: 'Calcium-Based Organic Nutrient Line',
    products: {
      seedling: [
        { name: "Medusa's Magic", ratio: 5.0, unit: 'ml/gal' },
        { name: 'Gaia Mania', ratio: 2.5, unit: 'ml/gal' },
      ],
      vegetative: [
        { name: "Medusa's Magic", ratio: 10.0, unit: 'ml/gal' },
        { name: 'Gaia Mania', ratio: 5.0, unit: 'ml/gal' },
        { name: 'Zeus Juice', ratio: 5.0, unit: 'ml/gal' },
      ],
      flowering: [
        { name: "Medusa's Magic", ratio: 10.0, unit: 'ml/gal' },
        { name: 'Herculean Harvest', ratio: 5.0, unit: 'ml/gal' },
        { name: 'Zeus Juice', ratio: 5.0, unit: 'ml/gal' },
      ],
      supplements: [
        {
          name: "Demeter's Destiny",
          ratio: 5.0,
          unit: 'ml/gal',
          optional: true,
        },
        { name: "Athena's Aminas", ratio: 5.0, unit: 'ml/gal', optional: true },
        {
          name: 'The Kraken',
          ratio: 5.0,
          unit: 'ml/gal',
          optional: true,
          floweringOnly: true,
        },
        {
          name: "Aphrodite's Extraction",
          ratio: 5.0,
          unit: 'ml/gal',
          optional: true,
          floweringOnly: true,
        },
      ],
    },
    strengthMultipliers: {
      light: 0.5,
      medium: 0.75,
      aggressive: 1.0,
    },
    targetEC: {
      seedling: { light: 0.3, medium: 0.5, aggressive: 0.7 },
      vegetative: { light: 0.8, medium: 1.2, aggressive: 1.6 },
      flowering: { light: 1.0, medium: 1.4, aggressive: 1.8 },
    },
    targetTDS: {
      seedling: { light: 150, medium: 250, aggressive: 350 },
      vegetative: { light: 400, medium: 600, aggressive: 800 },
      flowering: { light: 500, medium: 700, aggressive: 900 },
    },
    wateringMethodMultipliers: {
      'hand-watering': 1.0,
      'drip-system': 0.9,
      'bottom-wicking': 0.95,
      aeroponics: 0.7,
      'deep-water-culture': 1.0,
      'ebb-flow': 1.0,
    },
  },
};

module.exports = {
  nutrientBrands,
};
